name: NCAA Soccer Scraper

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC daily
  workflow_dispatch: # Allows manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Automated NCAA scores update $(date)"
          git push
        continue-on-error: true
